# -*- coding: utf-8 -*-
"""Resume Parsing - Retraining .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dQQP27zvNBYyTN5PLJAeBy3hq_Z9iIs

# Resume Parsing
Version 3.0

# Imports
"""

# !pip install PyMuPDF
# !pip install docx2pdf
# !pip install pdfx

import pandas as pd
from docx2pdf import convert
import pdfx
import sys


"""# Main"""

def main(data_path, resume_path, resume_category):
  ## Reading CSV
  resume_df = pd.read_csv(data_path)
  
  ## Reading Resume
  if resume_path.split(".")[1] == 'docx':
        convert(resume_path)
        resume_path = resume_path.split(".")[0] + ".pdf"
  elif resume_path.split(".")[1] == 'pdf':
      pass
  else:
      print("Only PDF and docx types are supported!")
      return
  
  doc = pdfx.PDFx(resume_path)

  text = doc.get_text()

  ## Adding resume to dataset
  final_df = resume_df.append({'ID' : resume_df["ID"].max() + 1,
                    'Resume_str' : text,
                    'Resume_html' : ' ',
                    'Category' : resume_category} , 
                    ignore_index=True)
  
  final_df.to_csv(data_path)

  return final_df

if __name__ == "__main__":
    args = sys.argv
    globals()[args[1]](*args[2:])

# main("Resume/Resume.csv", "osos.pdf", "HR")



